! ./node_modules/.bin/flow focus-check test/bad-cases/badkey.get.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/badkey.on.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/badkey.set.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/badval.set.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/connectas1.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/connectas2.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/connectas3.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/connectas4.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/connectas5.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/connectas6.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/stateless.badkey.get.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/stateless.badkey.get2.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/stateless.badkey.get3.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/stateless.badkey.set.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/stateless.badval.set.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/stateful.badkey.get.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/stateful.badkey.get2.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/stateful.badkey.set.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/stateful.badkey.set2.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/badstore.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/createConnectedStore.1.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/createConnectedStore.2.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/createConnectedStore.3.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/createConnectedStore.4.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/createConnectedStore.5.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/createConnectedStoreAs.1.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/createConnectedStoreAs.2.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/createConnectedStoreAs.3.flow.js
! ./node_modules/.bin/flow focus-check test/bad-cases/createConnectedStoreAs.4.flow.js
# ! ./node_modules/.bin/flow focus-check test/bad-cases/onincomponent.flow.js
